version: '3.8'

services:
  server:
    image: chaiminwoo0223/drugescape
    container_name: spring-boot-app
    environment:
      DB_JDBC_URL: ${DB_JDBC_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      GOOGLE_TOKEN_URL: ${GOOGLE_TOKEN_URL}
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_SECOND: ${ACCESS_SECOND}
      REFRESH_SECOND: ${REFRESH_SECOND}
    ports:
      - "8080:8080"
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 2048MB
    networks:
      - drugescape-network

networks:
  drugescape-network:
    driver: bridge