name: DrugEscape CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
    # 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # JDK 17 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # gradlew 파일 권한 지정
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Dockerhub 로그인
    - name: Sign in Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    # gradle bootBuildImage를 이용해 이미지를 만들고 원격 저장소에 Push
    - name: Build Docker image with Buildpack
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: ./gradlew bootBuildImage --imageName=${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}

  # ssh로 접속해 재배포
  Deploy:
    name: Deploy application
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote connect and Docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.REMOTE_HOST}}
        username: ${{secrets.REMOTE_SSH_ID}}
        key: ${{secrets.REMOTE_SSH_KEY}}
        passphrase: ${{secrets.REMOTE_SSH_PASSPHRASE}}
        port: ${{ secrets.REMOTE_SSH_PORT}}
        timeout: 40s
        script: |
          cd ${{secrets.REMOTE_DOCKER_PATH}}
          docker compose down
          docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}
          docker compose up -d
